apiVersion: v2
name: trivy-operator-polr-adapter
description: This Chart deploys trivy-operator Policy Reporter Adapter to your cluster.
version: 0.8.1
type: application
dependencies:
  - name: trivy-operator-polr-adapter
    version: 0.8.0
    repository: https://fjogeleit.github.io/trivy-operator-polr-adapter