trivy-operator:
  # -- targetNamespace defines where you want trivy-operator to operate. By
  # default, it's a blank string to select all namespaces, but you can specify
  # another namespace, or a comma separated list of namespaces.
  targetNamespaces: "gha-runner"

  operator:
    # -- metricsFindingsEnabled the flag to enable metrics for findings
    metricsFindingsEnabled: true

    # -- metricsVulnIdEnabled the flag to enable metrics about cve vulns id
    # be aware of metrics cardinality is significantly increased with this feature enabled.
    metricsVulnIdEnabled: true

    # -- exposedSecretScannerEnabled the flag to enable exposed secret scanner
    exposedSecretScannerEnabled: true

    # -- MetricsExposedSecretInfo the flag to enable metrics about exposed secrets
    # be aware of metrics cardinality is significantly increased with this feature enabled.
    metricsExposedSecretInfo: true

    # -- MetricsConfigAuditInfo the flag to enable metrics about configuration audits
    # be aware of metrics cardinality is significantly increased with this feature enabled.
    metricsConfigAuditInfo: true

    # -- MetricsRbacAssessmentInfo the flag to enable metrics about Rbac Assessment
    # be aware of metrics cardinality is significantly increased with this feature enabled.
    metricsRbacAssessmentInfo: true

    # -- MetricsInfraAssessmentInfo the flag to enable metrics about Infra Assessment
    # be aware of metrics cardinality is significantly increased with this feature enabled.
    metricsInfraAssessmentInfo: true

    # -- MetricsImageInfo the flag to enable metrics about Image Information of scanned images
    # This information has image os information including os family, name/version, and if end of service life has been reached
    # be aware of metrics cardinality is significantly increased with this feature enabled.
    metricsImageInfo: true

    # -- MetricsClusterComplianceInfo the flag to enable metrics about Cluster Compliance
    # be aware of metrics cardinality is significantly increased with this feature enabled.
    metricsClusterComplianceInfo: true

    # -- mergeRbacFindingWithConfigAudit the flag to enable merging rbac finding with config-audit report
    mergeRbacFindingWithConfigAudit: true

  # -- Prometheus ServiceMonitor configuration -- to install the trivy operator with the ServiceMonitor
  # you must have Prometheus already installed and running. If you do not have Prometheus installed, enabling this will
  # have no effect.
  serviceMonitor:
    # -- enabled determines whether a serviceMonitor should be deployed
    enabled: true
    # -- The namespace where Prometheus expects to find service monitors
    namespace: observability

  trivy:
    # -- storageClassName is the name of the storage class to be used for trivy server PVC. If empty, tries to find default storage class
    storageClassName: "default"

    # -- storageSize is the size of the trivy server PVC
    storageSize: "5Gi"

    # -- severity is a comma separated list of severity levels reported by Trivy.
    severity: HIGH,CRITICAL

    # -- slow this flag is to use less CPU/memory for scanning though it takes more time than normal scanning. It fits small-footprint
    slow: true
    # -- ignoreUnfixed is the flag to show only fixed vulnerabilities in
    # vulnerabilities reported by Trivy. Set to true to enable it.
    #
    ignoreUnfixed: true

    # -- resources resource requests and limits for scan job containers
    resources:
      requests:
        cpu: 
        memory: 100M
        # ephemeralStorage: "2Gi"
      limits:
        cpu: 
        memory: 500M
        # ephemeralStorage: "2Gi"

  nodeCollector:
    # -- tolerations to be applied to the node-collector so that they can run on nodes with matching taints
    tolerations:
      - key: "nodegroup-role"
        operator: "Exists"