{{- define "base-chart.deployment" -}}
{{- if not .Values.argoRollouts.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-chart.fullname" . }}
  namespace: {{ include "base-chart.namespace" . }}
  labels:
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.datadogLabels.enabled }}
    tags.datadoghq.com/env: "{{ .Values.datadogLabels.env }}"
    tags.datadoghq.com/service: "{{ .Values.datadogLabels.service }}"
    tags.datadoghq.com/version: "{{ .Values.image.tag }}"
    {{- end }}
    {{- include "base-chart.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- include "deployment-spec" . | trim | nindent 2 }}
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}