{{- define "base-chart.external-secret" -}}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "base-chart.fullname" . }}
  namespace: {{ include "base-chart.namespace" . }}
  labels:
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "base-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  {{- with .Values.externalSecret.secretStoreRef }}
  secretStoreRef:
    kind: {{ .kind }}
    name: {{ .name }}
  {{- end }}
  target:
    name: {{ include "base-chart.fullname" . }}-external-secret
    creationPolicy: {{ .Values.externalSecret.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.deletionPolicy }}
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.secretName }}
{{- end }}
{{- end }}