{{- define "base-chart.ingress" -}}
{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "base-chart.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $paths := .Values.ingress.paths -}}
{{- $extraPaths := .Values.ingress.extraPaths -}}
{{- $pathType := .Values.ingress.pathType -}}
apiVersion: {{ include "base-chart.apiVersion.ingress" . }}
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ include "base-chart.fullname" . }}
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
    {{- if .Values.ingress.labels }}
    {{- toYaml .Values.ingress.labels | nindent 4 }}
    {{- end }}
spec:
  {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          {{- if $extraPaths }}
          {{- toYaml $extraPaths | nindent 10 }}
          {{- end }}
          {{- range $p := $paths }}
          - path: {{ $p }}
            {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
              service:
                name: {{ include "base-chart.fullname" $ }}
                port:
                  {{- if kindIs "float64" $servicePort }}
                  number: {{ $servicePort }}
                  {{- else }}
                  name: {{ $servicePort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ include "base-chart.fullname" $ }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end -}}
    {{- end -}}
  {{- else }}
    - http:
        paths:
          {{- if $extraPaths }}
          {{- toYaml $extraPaths | nindent 10 }}
          {{- end }}
          {{- range $p := $paths }}
          - path: {{ $p }}
            {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
              service:
                name: {{ include "base-chart.fullname" $ }}
                port:
                  {{- if kindIs "float64" $servicePort }}
                  number: {{ $servicePort }}
                  {{- else }}
                  name: {{ $servicePort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ include "base-chart.fullname" $ }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end -}}
  {{- end -}}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- if and .Values.argoRollouts.enabled .Values.argoRollouts.previewHosts }}
apiVersion: {{ include "base-chart.apiVersion.ingress" . }}
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ include "base-chart.fullname" . }}-preview
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
    {{- if .Values.ingress.labels }}
    {{- toYaml .Values.ingress.labels | nindent 4 }}
    {{- end }}
spec:
  {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- end }}
  rules:
  {{- if .Values.argoRollouts.previewHosts }}
    {{- range $host := .Values.argoRollouts.previewHosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          {{- if $extraPaths }}
          {{- toYaml $extraPaths | nindent 10 }}
          {{- end }}
          {{- range $p := $paths }}
          - path: {{ $p }}
            {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
              service:
                name: {{ include "base-chart.fullname" $ }}-preview
                port:
                  {{- if kindIs "float64" $servicePort }}
                  number: {{ $servicePort }}
                  {{- else }}
                  name: {{ $servicePort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ include "base-chart.fullname" $ }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end -}}
    {{- end -}}
  {{- else }}
    - http:
        paths:
          {{- if $extraPaths }}
          {{- toYaml $extraPaths | nindent 10 }}
          {{- end }}
          {{- range $p := $paths }}
          - path: {{ $p }}
            {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if eq (include "base-chart.apiVersion.ingress" $) "networking.k8s.io/v1" }}
              service:
                name: {{ include "base-chart.fullname" $ }}-preview
                port:
                  {{- if kindIs "float64" $servicePort }}
                  number: {{ $servicePort }}
                  {{- else }}
                  name: {{ $servicePort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ include "base-chart.fullname" $ }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end -}}
  {{- end -}}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
