{{- define "base-chart.rbac" -}}
{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.namespaced | ternary "Role" "ClusterRole" }}
metadata:
  name: {{ include "base-chart.fullname" . }}
  {{- if .Values.rbac.namespaced }}
  namespace: {{ include "base-chart.namespace" . }}
  {{- end }}
  labels:
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "base-chart.labels" . | nindent 4 }}
rules:
{{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 0 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.namespaced | ternary "RoleBinding" "ClusterRoleBinding" }}
metadata:
  name: {{ include "base-chart.fullname" . }}
  {{- if .Values.rbac.namespaced }}
  namespace: {{ include "base-chart.namespace" . }}
  {{- end }}
  labels:
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "base-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.rbac.namespaced | ternary "Role" "ClusterRole" }}
  name: {{ include "base-chart.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "base-chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}