{{- define "base-chart.secret-provider-class" -}}
{{- if .Values.secretCsi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "base-chart.fullname" . }}
  namespace: {{ include "base-chart.namespace" . }}
  labels:
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "base-chart.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secretCsi.provider }}
  parameters:
    objects: |
      - objectName: "{{ .Values.secretCsi.secretName }}"
        objectType: "{{ .Values.secretCsi.secretType }}"
        {{- if .Values.secretCsi.keys }}
        jmesPath:
          {{- range $key := .Values.secretCsi.keys }}
          - path: {{ $key }}
            objectAlias: {{ $key }}
          {{- end }}
        {{- end }}
  secretObjects:
  - secretName: {{ include "base-chart.fullname" . }}-secret-csi
    type: Opaque
    {{- if .Values.secretCsi.keys }}
    data:
      {{- if or .Values.secretCsi.labels .Values.secretCsi.annotations }}
      - metadata:
          {{- with .Values.secretCsi.labels }}
          labels:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.secretCsi.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- range $key := .Values.secretCsi.keys }}
      - key: {{ $key }}
        objectName: {{ $key }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}