{{- define "base-chart.secret" -}}
{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-chart.fullname" . }}
  namespace: {{ include "base-chart.namespace" . }}
  labels:
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "base-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}